### PR TITLE
fix issue in case when namespace has no prefix

### PR DESCRIPTION
**Pull request by git9527**
@cjbarth please check the PR

### CODE REVIEW

**Review by cjbarth — APPROVED** [review]

**Comment by cjbarth** [comment]
Can you do me a favor and make a PR against this branch with these changes too? That would help prevent this code from being lost during the migration to TS.

https://github.com/node-saml/xml-crypto/pull/325

**Comment by git9527** [comment]
I've loved to, but there're some error when executing `npm install` on your `ts-convert` branch
Screenshot 2023-07-08 at 15 54 36

Could you help merge these changes and perform new release? Meanwhile help me resolve the ts issues, I can sync changes there

**Comment by cjbarth** [comment]
> Meanwhile help me resolve the ts issues, I can sync changes there

I'm working on this. It seems there are a few more types that need to be tightened up and otherwise corrected.

**Comment by cjbarth** [comment]
@git9527 , don't worry about the compilation errors, just make a PR against #325 and I'll fix that kind of stuff when I'm working on the other stuff. I just don't want to have to fiddle with the .js -> .ts rename stuff causing a merge conflict. There is no way to automatically resolve that, so  PR that would do that would be super helpful.

**Comment by git9527** [comment]
@cjbarth please check https://github.com/cjbarth/xml-crypto/pull/3

**Comment by cjbarth** [comment]
@git9527 Thank you so much for that. #336 is the last PR waiting to land before I release 3.x. However, it is a simple PR, so I may just do it for them, since it is a cherry pick PR, so that I can unblock you.

**Pull request merged**
