### PR TITLE
fix issue in case when namespace has no prefix

### PR DESCRIPTION
**Pull request by git9527**

### CODE REVIEW

**Comment by cjbarth** [comment]
@git9527 , please lint this code: `npm run prettier-format`. Thanks for your contribution!

**Comment by git9527** [comment]
@cjbarth Can you schedule one release after this merge? I've got one project highly depend on this, thanks

**Comment by cjbarth** [comment]
I can, but not from master, as that would have to be a semver-major release. If you want this on the 3.x branch, please also make a PR against that branch. I can release from there.

**Comment by git9527** [comment]
can you create 3.x branch? I've submitted the linted code

**Comment by cjbarth** [comment]
> can you create 3.x branch?

Done.

**Comment by git9527** [comment]
@cjbarth Updated the base brach, please merge and release, thanks

**Comment by git9527** [comment]
Don't worry. Let me create new fork. And create feature vranch based on 3.x. Then raise the PR



---Original---
From: "Chris ***@***.***&gt;
Date: Thu, Jul 6, 2023 21:07 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [node-saml/xml-crypto] fix issue in case when namespace has noprefix (PR #326)




 
I think there might have been a miscommunication on how we have to do this. First we have to get your code landed on master. After that, we can land another PR with the same changes against the 3.x branch. We don't want to pull master changes over to the 3.x branch and we don't want to land anything on the 3.x branch that isn't already on master.

**Pull request closed without merging**
