### PR TITLE
Exports C14nCanonicalization, ExclusiveCanonicalization

### PR DESCRIPTION
**Pull request by cjbarth**
Same changes as #335 on to `master`.

### CODE REVIEW

**Comment by cjbarth** [comment]
@angeljqv can you lint this and then we can merge it? `npm run prettier-format`

**Review by LoneRifle — APPROVED** [review]

**Review by LoneRifle — CHANGES_REQUESTED** [review]
@angeljqv - please run `npm run lint:fix` on your code to make your code acceptable, so that our automated tests pass

**Comment by parallels999** [comment]
hi @cjbarth, this PRs has no effect on v4

**Comment by cjbarth** [comment]
@parallels999 , are you identifying a problem or concern? I don't understand the nature of your comment.

**Comment by parallels999** [comment]
https://github.com/node-saml/xml-crypto/blob/6e6a8b0e36f0d281fe5c402125e98684a6690855/CHANGELOG.md?plain=1#L23-L25

Just concern, i am reading v4 changelog, and this is not available in v4, but it works in v3

**Comment by cjbarth** [comment]
That is an oversight (or bad merge) then, sorry about that. Feel free to put up a PR against `master` again and I'll merge it in and do a 4.1 release (adding a feature). Thanks!

**Pull request merged**
