### PR TITLE
Add support for directly querying a node to see if it has passed validation

### PR DESCRIPTION
**Pull request by cjbarth**
Previously, the API for checking if a reference was valid was very complex. This adds support for allow for a single method call on the container that represents the reference to determine if it passed validation. The idea is that this can clean up some code as found at `node-saml`:

```typescript
export const validateXmlSignatureForCert = (
  signature: Node,
  certPem: string,
  fullXml: string,
  currentNode: Element
): boolean => {
  const sig = new xmlCrypto.SignedXml();
  sig.keyInfoProvider = {
    file: "",
    getKeyInfo: () => "<X509Data></X509Data>",
    getKey: () => Buffer.from(certPem),
  };
  sig.loadSignature(signature);
  // We expect each signature to contain exactly one reference to the top level of the xml we
  //   are validating, so if we see anything else, reject.
  if (sig.references.length != 1) return false;
  const refUri = sig.references[0].uri;
  assertRequired(refUri, "signature reference uri not found");
  const refId = refUri[0] === "#" ? refUri.substring(1) : refUri;
  // If we can't find the reference at the top level, reject
  const idAttribute = currentNode.getAttribute("ID") ? "ID" : "Id";
  if (currentNode.getAttribute(idAttribute) != refId) return false;
  // If we find any extra referenced nodes, reject.  (xml-crypto only verifies one digest, so
  //   multiple candidate references is bad news)
  const totalReferencedNodes = xpath.selectElements(
    currentNode.ownerDocument,
    "//*[@" + idAttribute + "='" + refId + "']"
  );

  if (totalReferencedNodes.length > 1) {
    return false;
  }
  fullXml = normalizeNewlines(fullXml);
  return sig.checkSignature(fullXml);
};
```

Which code follows the recommendation in the README:

```javascript
// Roll your own
var elem = xpath.select("/xpath_to_interesting_element", doc);
var uri = sig.references[0].uri; // might not be 0 - depending on the document you verify
var id = uri[0] === "#" ? uri.substring(1) : uri;
if (elem.getAttribute("ID") != id && elem.getAttribute("Id") != id && elem.getAttribute("id") != id)
  throw new Error("the interesting element was not the one verified by the signature");

// Use the built-in method
let elem = xpath.select("/xpath_to_interesting_element", doc);
try {
  const matchingReference = sig.validateElementAgainstReferences(elem, doc);
} catch {
  throw new Error("the interesting element was not the one verified by the signature");
}
```

Since we already know about the `id` internally, this shouldn't have to be re-implemented by a consumer.

### CODE REVIEW

**Comment by cjbarth** [comment]
@LoneRifle If you like this approach, or think a feature like this has merit, I'll add some tests.

**Comment by LoneRifle** [comment]
My dev tooling is not within reach currently; will be a few days before I can get round to looking!

**Comment by cjbarth** [comment]
@LoneRifle , I'm eager to hear what you think. I'd like to get this landed and released so that I can use it in the pending release of `node-saml`. I appreciate you buying out time to have a look.

**Review by LoneRifle — APPROVED** [review]
lgtm, but how is this going to be used? Should we update the README to explain the new feature?

**Comment by cjbarth** [comment]
Yes, I'd update the README with this new process. I'll actually write a test that shows the old way working to validate and the new way working to validate. Now that you're OK with the general direction, I'll start to move forward on the README and tests.

**Comment by cjbarth** [comment]
I've finished with this code and am breaking it into smaller pieces to land as functional commits and to make review easier.

**Comment by cjbarth** [comment]
@LoneRifle Hopefully this gives a clearer idea of how this would be used. Please have a look and approve this again if you agree with this methodology. I'm 100% read to land this unless you have feedback.

After this, I'll make a PR for pulling `isDomNode` from NPM instead of GitHub, and then we can release this as a semver-major and get on to `node-saml` work :)

**Review by LoneRifle — APPROVED** [review]
Lgtm

**Pull request merged**
