### PR TITLE
Set `getCertFromKeyInfo` to `noop`

### PR DESCRIPTION
**Pull request by cjbarth**
`getKeyInfoContent` was incorectly set to `noop` instead of `getCertFromKeyInfo`

### CODE REVIEW

**Comment by cjbarth** [comment]
This PR addresses the concerns correctly pointed out by @srd90 [here](https://github.com/node-saml/node-saml/pull/341#issuecomment-1904714894).

Since it is fixing a mistake, and it seems few, if any are using it, should this be a semver-minor change or a semver-major change @LoneRifle ?

**Review by LoneRifle — DISMISSED** [review]
lgtm, thanks for the catch @srd90 !

**Comment by cjbarth** [comment]
@LoneRifle , do you think I should release this as a semver-minor or semver-major release?

**Comment by LoneRifle** [comment]
Inclination is towards a major release, given that it's likely a breaking change. At the same time, you could consider deprecating v5 so that users are encouraged to skip it

**Comment by cjbarth** [comment]
Honestly, I think we de-facto deprecate anything other than the current semver-major release. I suppose I can actively deprecate these on NPM though. I have no interest in trying to support anything other the HEAD or the latest release. If someone wants something on an older version, they can make the correct PR, but that is on them.

@LoneRifle what has been your tradition here?

**Comment by LoneRifle** [comment]
@cjbarth - I've usually just left versions alone,  but only because I previously saw no significant security issues. I'm happy to defer to you to set the norm going forward

**Pull request merged**
